services:
  spring-boot-crud-sql:
    image: openjdk:17-jdk-slim # Use a pre-built Java image
    container_name: spring-boot-app
    ports:
      - "8081:8081" # Maps host port 8081 to container port 8081
    volumes:
      - ./target/spring-boot-crud-0.0.1-SNAPSHOT.jar:/app/spring-boot-crud-sql.jar # Update with your actual JAR file name
    command: ["java", "-jar", "/app/spring-boot-crud-sql.jar"] # Update with your actual JAR file name
    networks:
      - spring-boot-crud-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: spring-boot-crud-sql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-boot-crud-network

networks:
  spring-boot-crud-network:
    driver: bridge

volumes:
  postgres_data: