server:
  port: 8081
spring:
  application:
    name: Spring-boot-crud-with-relational-DB
  profiles:
    active:
      - postgres

management:
  endpoints:
    web:
      exposure:
#        include: health,info  # Include specific endpoints
         include: '*'  # Include all endpoints
        # exclude: beans,env  # Exclude specific endpoints
      base-path: /manage
      request:
        request-logging:
          enabled: true
  cors:
    allowed-origins: http://localhost:8080
    allowed-methods: GET,POST
